### PR TITLE
Add a function to move to the next available page (fixing issue)

### LINKED ISSUE #2: remove duplicates

### LINKED ISSUE #3: Page does not increment
When using this, the page doesn't actually increment, it scans the same page over and over again.

I don't see anything to actually move page, just to click on cards on a singular page?

### PR DESCRIPTION
**Pull request by BillyDotWS**
Added a function to move to a given page and added a usage at the bottom of the page loop.

This has been tested and works perfectly.

Fixes #3 
Fixes #2

### CODE REVIEW

File: content/linkedin-scraper.js [hunk 1]
```diff
@@ -120,5 +129,7 @@ async function scrapeLinkedInJobs() {
 
       sendProgressPercentage(overallProgressPercentage);
     }
+
+    await changePage(pageIndex+2);
```
Comment (akramaznakour) [inline content/linkedin-scraper.js:133]: Hey @BillyDotWS, thanks for the PR! Just a quick suggestion: let's add a condition to avoid navigating to the next page if we're already on the last one. Appreciate your contribution!

```suggestion

    if (pageIndex < pageCount - 1) {
      await changePage(pageIndex + 2);
    }
```

Comment (BillyDotWS) [reply content/linkedin-scraper.js]: Good point, didn't notice this possibility, committed suggestion 👍

**Review by akramaznakour — APPROVED** [review]

File: content/linkedin-scraper.js (hunk 1 above)
Comment (akramaznakour) [reply content/linkedin-scraper.js]: Thanks
